name: Web App

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - "Frontend/**"

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./main/Frontend"

    steps:
      # Checkout main branch
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install dependencies
        run: npm install

      - name: Build angular
        run: npm run build -- --prod

      - name: Build docker
        run: npm run docker-build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: npm run docker-push

      # Checkout chart repo
      - name: Checkout chart-repo
        uses: actions/checkout@v2
        with:
          ref: 'chart-repo'
          path: chart-repo

      - name: Create fresh helm chart
        run: npm run helm-build -- -d $GITHUB_WORKSPACE/chart-repo
      
      - name: Register chart in repository
        run: npm run helm-index -- $GITHUB_WORKSPACE/chart-repo --url https://mauriceackel.github.io/CKDAC

      # Push to chart repo
      - name: Push to chart-repo
        run: |
          cd $GITHUB_WORKSPACE/chart-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated chart repository"
          COUNTER=0
          while [[ $(git push | echo $?) && $COUNTER -lt 3 ]]; do
            git reset HEAD~1
            git checkout index.yaml
            git stash
            git pull
            git checkout stash -- .
            npm --prefix $GITHUB_WORKSPACE/main/Backend/User\ Service run helm-index -- $GITHUB_WORKSPACE/chart-repo --url https://mauriceackel.github.io/CKDAC
            git add .
            git commit -m "Updated chart repository"
            ((COUNTER=COUNTER+1))
          done;
